version: "2"
services:
  stars:
    container_name: stars
    restart: always
    build: .
    ports:
      - "8081:8081"
    links:
      - stars_db
  stars_db:
    container_name: stars_db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"